#' Append weights generated by iterake to original data
#' 
#' This function appends the created weights from \code{iterake()} to the original data file that
#' was used in \code{universe()}.
#' 
#' @param iterake Output object created with \code{iterake()} function.
#' @param wgt_name Name given to column of weights to be added to data, default is "weight".
#' 
#' @importFrom dplyr mutate
#' @importFrom glue glue
#' @importFrom rlang !! := abort
#' @importFrom tibble as_tibble
#' 
#' @return A \code{tibble} consisting of the original data plus the column of weights.
#' 
#' @export
append_weights <- function(
        iterake, wgt_name = "weight"
) {
    # some error checking
    if (any(
        length(wgt_name) > 1,
        !is.character(wgt_name)
    )) {
        
        abort("Input to `wgt_name` must be a single character string.")
    }
    
    if (wgt_name %in% names(iterake$universe$data$data)) {
        abort(glue("Column name '{wgt_name}' already exists in the data. Please supply a different name to `wgt_name`."))
    }
    
    if (is.null(iterake$summary)) {
        abort("No weights were generated to append. Rerun `iterake()`.")
    }
    
    # is the as_tibble part necessary? better placed in universe maybe?
    iterake$universe$data$data |>
        as_tibble() |>
        mutate(!!wgt_name := iterake$results)
    
}