#' Summary weight statistics
#' 
#' This function creates a `tibble` containing information pertaining to a set of weights. It includes
#' sample size, weighted sample size, effective sample size, as well as loss and efficiency values.
#' 
#' @param x Output of `iterake()`.
#' 
#' @importFrom rlang abort
#' 
#' @return A `tibble` containing unweighted and weighted sample size, effective sample size, and
#' efficiency and loss values for the weights generated by `iterake()`.
#' 
#' @export
weight_stats <- function(x) {
    
    if (!inherits(x, "iterake")) {
        abort("Input to `x` must be the output of `iterake()`.")
    }
    
    x$summary
    
}
