#' Generate summary statistics for generated weights
#' 
#' This function creates a tibble containing information pertaining to a set of weights. It includes
#' sample size, weighted sample size, effective sample size, as well as loss and efficiency values.
#' 
#' @param iterake Output object created with \code{iterake()} function.
#' 
#' @importFrom rlang abort
#' 
#' @return A tibble containing unweighted and weighted sample size, effective sample size, and
#' efficiency and loss values for the weights generated by iterake.
#' 
#' @export
weight_stats <- function(iterake) {
    
    its.a.rake <- inherits(iterake, "iterake")
    
    if (!its.a.rake) {
        abort("Input to `iterake` must be the output of `iterake()`.")
    }
    
    iterake$summary
    
}
